module.exports = {
  "REGISTER": "REGISTER",
  "FORGOT_PASSWORD": "FORGOT_PASSWORD",
  "TWOFA": "TWOFA",
  "UNSUBSCRIBE": "UNSUBSCRIBE",
  "KYC_AUTHENTICATION": "KYC_AUTHENTICATION",
  "SSO_TOKEN": "SSO_TOKEN",
};
