module.exports = {
  GENERATE_WALLET: "GENERATE_WALLET",
  IMPORT_WALLET: "IMPORT_WALLET",
  STAKING: "STAKING",
  GENERATE_AFFILIATE_CODE: "GENERATE_AFFILIATE_CODE",
  AFFILIATE_REWARD: "AFFILIATE_REWARD"
}